In [2]:
import numpy as np

In [3]:
print(np.__version__)

2.5.2


In [4]:
# Creating arrays
list1=[1,2,3]
print(list1)

[1, 2, 3]


In [6]:
arr_list1 = np.array(list1)
print(arr_list1)

[1 2 3]


In [7]:
print(type(arr_list1))

<class 'numpy.ndarray'>


In [9]:
list1=[1,2,3]
list2=[4,5,6]
arr_list2= np.array([list1,list2])
print(arr_list2)

[[1 2 3]
 [4 5 6]]


In [15]:
list1=[1,2,3]
list2=[4,5,6]
list3=[7,8,9]
arr_list3= np.array([[list1,list2,list3]])
print(arr_list3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [17]:
print(arr_list3.ndim) #to check which dimension array is this

3


In [18]:
# numpy array attributes
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [21]:
print("shape",arr1.shape)
print("size",arr1.size)
print("data types",arr1.dtype)
print("n_dim",arr1.ndim)

shape (2, 3)
size 6
data types int64
n_dim 2
