In [2]:
import numpy as np

In [3]:
print(np.__version__)

2.5.2


In [4]:
# Creating arrays
list1=[1,2,3]
print(list1)

[1, 2, 3]


In [6]:
arr_list1 = np.array(list1)
print(arr_list1)

[1 2 3]


In [7]:
print(type(arr_list1))

<class 'numpy.ndarray'>


In [9]:
list1=[1,2,3]
list2=[4,5,6]
arr_list2= np.array([list1,list2])
print(arr_list2)

[[1 2 3]
 [4 5 6]]


In [15]:
list1=[1,2,3]
list2=[4,5,6]
list3=[7,8,9]
arr_list3= np.array([[list1,list2,list3]])
print(arr_list3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [17]:
print(arr_list3.ndim) #to check which dimension array is this

3


In [18]:
# numpy array attributes
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [21]:
print("shape",arr1.shape)
print("size",arr1.size)
print("data types",arr1.dtype)
print("n_dim",arr1.ndim)

shape (2, 3)
size 6
data types int64
n_dim 2


In [22]:
# Array initialization methods


In [23]:
zero_arr =np.zeros((2,3))
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [24]:
one_arr = np.ones((2,3))
print(one_arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [25]:
# full array

In [26]:
full_arr = np.full((3,2),7)
print(full_arr)

[[7 7]
 [7 7]
 [7 7]]


In [27]:
# Identity Matrix

In [28]:
id_arr = np.eye(3)
print(id_arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
# empty array

In [30]:
emp_arry = np.empty(2)
print(emp_arry)

[3.12005461e-315 0.00000000e+000]


In [36]:
# evenly spaced array
print(np.arange(1,5,3)) #from 1-5 with the space of 3

[1 4]


In [38]:
# random values array

random_arr = np.random.rand(3,2)
print(random_arr)

[[0.64983787 0.49442573]
 [0.13631334 0.18637995]
 [0.56513218 0.1809161 ]]


In [42]:
random_arr = np.random.randint(1,10,(4,4))
print(random_arr)

[[1 7 9 3]
 [9 4 7 4]
 [8 8 7 3]
 [9 1 7 4]]


In [43]:
# Array indexing and slicing

In [44]:
a= np.array([1,3,5,7,9])
print(a)

[1 3 5 7 9]


In [47]:
print(a[3])

7


In [49]:
# slicing
# array[start:stop:step]

In [51]:
print(a[0:3])

[1 3 5]


In [52]:
print(a[0:3:2])

[1 5]


In [54]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [59]:
print(arr2[1][2])

6


In [ ]:
print(arr2[1:]) # to show two dimension array 1: 

[[4 5 6]]


In [62]:
print(arr2[:, 2]) #before comma it is rows and after that it is columns

[3 6]


In [63]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [71]:
print("first",arr3[:,0])
print("second",arr3[:,1])
print("third",arr3[:,2])

first [1 4 7]
second [2 5 8]
third [3 6 9]


In [72]:
print(arr3[0][2])

3


In [73]:
# Array Reshaping and Flatening

In [80]:
arr1=np.array([1,2,3,4,5,6])
print(arr1)

[1 2 3 4 5 6]


In [82]:
reshaped = arr1.reshape((6,1))
print(reshaped)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [83]:
reshaped2 = arr1.reshape(2,3)
print(reshaped2)

[[1 2 3]
 [4 5 6]]


In [84]:
# Flatening

In [86]:
print(reshaped2.flatten()) # flatening changed multi dimension to single dimension

[1 2 3 4 5 6]


In [87]:
# Array Stacking and splitting

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [ ]:
print(np.vstack((a,b))) # vertical stacking - row wise
print(np.hstack((a,b))) # horizontal stacking - column wise

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [94]:
#splitting
c= np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [96]:
print(np.hsplit(c,3))

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [97]:
vsplit = np.vsplit(c,2)
for s in vsplit:
    print(s)

[[1 2 3]]
[[4 5 6]]


In [98]:
# Mathematical operations on array

In [100]:
a= np.array([10,20,-30,40])
print(a)

[ 10  20 -30  40]


In [101]:
print(a+10)
print(a-30)
print(a*2)
print(a/10)

[ 20  30 -20  50]
[-20 -10 -60  10]
[ 20  40 -60  80]
[ 1.  2. -3.  4.]


In [102]:
b =  np.array([1,4,9])
print(b)

[1 4 9]


In [103]:
print(np.square(b))
print(np.sqrt(b))

[ 1 16 81]
[1. 2. 3.]


In [105]:
# Statical functions

In [106]:
a=np.array([[1,2,3],[4,5,7]])
print(a)

[[1 2 3]
 [4 5 7]]


In [107]:
print(sum(a))

[ 5  7 10]


In [109]:
print(np.median(a))
print(np.mean(a))
print(np.std(a))
print(np.min(a))
print(np.max(a))


3.5
3.6666666666666665
1.9720265943665387
1
7


In [110]:
# Array Comparision
a=np.array([1,2,3])
b=np.array([4,5,6])

print(a)
print(b)

[1 2 3]
[4 5 6]


In [113]:
print(a==b)
print(np.array_equal(a,b))

[False False False]
False


In [114]:
# Handling null values

In [115]:
data1 = np.array([1,2,np.nan,4,np.inf])

In [116]:
print(data1)

[ 1.  2. nan  4. inf]


In [117]:
print(np.isnan(data1))

[False False  True False False]


In [118]:
print(np.nan_to_num(data1))

[1.00000000e+000 2.00000000e+000 0.00000000e+000 4.00000000e+000
 1.79769313e+308]


In [119]:
# Save and load arrays

In [120]:
arr = np.array([1,0,0,8])
print(arr)
np.save("My array.npy",arr)

[1 0 0 8]


In [124]:
loaded_arr = np.load('My array.npy')
print(loaded_arr)

[1 0 0 8]
